### ISSUE TITLE
Hi ... keine Tokens usw. in öffentlichen Repos...

### ISSUE THREAD

**Issue by noibi** [skizz666/myLibrary#1]
Kleiner Tipp, in öffentliche Repos sollte meine keine Tokes, keys, PW's usw. pushen.
Man könnte sie Missbrauchen. ;)

**Comment by skizz666** [comment]
Danke für die Info, das werde ich bei Gelegenheit noch ändern :-)

Christian Tiefert ***@***.***> schrieb am Di., 26. Sept.
2023, 08:35:
